### ISSUE TITLE
Separate out data storage backends?

### ISSUE THREAD

**Issue by dwlnetnl** [tidwall/finn#5]
What are your ideas on separating out the different data storage backends? My reasoning is to have less dependencies in the code. Maybe it's a good thing to have a reasonable default choice, fastlog.

**Comment by tidwall** [comment]
Unfortunately, I don't have any plans to break apart the backends any time soon. Once I get the codebase matched up with hashicorp/raft v1.0, I might come back around and do some housekeeping.
